function fig_configure
%FIG_CONFIGURE Window for the configuration of settings
%   License: https://darma.codeplex.com/license

    global settings;
    % Create and maximize annotation window
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    handles.figure_configure = figure( ...
        'Name','DARMA: Configure', ...
        'Units','normalized', ...
        'Position',[0.25 0.25 0.50 0.50], ...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'ToolBar','none', ...
        'Visible','off', ...
        'Color',defaultBackground);
    %Buttons
    handles.push_submit = uicontrol(...
        'Parent',handles.figure_configure,...
        'Units','normalized',...
        'Position',[.6 .025 .3 .05],...
        'String','Submit Changes',...
        'Callback',@push_submit_Callback);
    handles.push_cancel = uicontrol(...
        'Parent',handles.figure_configure,...
        'Units','normalized',...
        'Position',[.1 .025 .3 .05],...
        'String','Cancel Changes',...
        'Callback','delete(gcf); return;');
    %Left Panel
    panel_left = uipanel(...
        'Parent',handles.figure_configure,...
        'Units','normalized',...
        'Position',[.05 .1 .40 .85],...
        'Title','Settings');
    % % Sampling Subpanel
    handles.panel_sps = uipanel( ...
        'Parent',panel_left, ...
        'Position',[.1 .85 .8 .1],...
        'Title','Samples per Second');
    handles.bgroup_sps = uibuttongroup(handles.panel_sps, ...
        'Units','normalized', ...
        'Position',[0 0 1 1], ...
        'BorderType','none', ...
        'Visible','off');
    handles.sample_1per4 = uicontrol(handles.bgroup_sps, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02 0 1/5 1], ...
        'String','0.25', ...
        'HandleVisibility','off');
    handles.sample_1per2 = uicontrol(handles.bgroup_sps, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+1/5 0 1/5 1], ...
        'String','0.50', ...
        'HandleVisibility','off');
    handles.sample_1per1 = uicontrol(handles.bgroup_sps, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+2/5 0 1/5 1], ...
        'String','1.00', ...
        'HandleVisibility','off');
    handles.sample_2per1 = uicontrol(handles.bgroup_sps, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+3/5 0 1/5 1], ...
        'String','2.00', ...
        'HandleVisibility','off');
    handles.sample_4per1 = uicontrol(handles.bgroup_sps, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+4/5 0 1/5 1], ...
        'String','4.00', ...
        'HandleVisibility','off');
    set(handles.bgroup_sps,'Visible','on');
    %Magnitude Subpanel
    handles.panel_mag = uipanel( ...
        'Parent',panel_left, ...
        'Position',[.1 .7 .8 .1],...
        'Title','Axis Magnitude');
    handles.bgroup_mag = uibuttongroup(handles.panel_mag, ...
        'Units','normalized', ...
        'Position',[0 0 1 1], ...
        'BorderType','none', ...
        'Visible','off');
    handles.mag_1 = uicontrol(handles.bgroup_mag, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02 0 1/4 1], ...
        'String','1', ...
        'HandleVisibility','off');
    handles.mag_10 = uicontrol(handles.bgroup_mag, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+1/4 0 1/4 1], ...
        'String','10', ...
        'HandleVisibility','off');
    handles.mag_100 = uicontrol(handles.bgroup_mag, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+2/4 0 1/4 1], ...
        'String','100', ...
        'HandleVisibility','off');
    handles.mag_1000 = uicontrol(handles.bgroup_mag, ...
        'Style','radiobutton', ...
        'Units','normalized', ...
        'Position',[.02+3/4 0 1/4 1], ...
        'String','1000', ...
        'HandleVisibility','off');
    set(handles.bgroup_mag,'Visible','on');
    %Right Panel
    panel_right = uipanel(...
        'Parent',handles.figure_configure,...
        'Units','normalized',...
        'Position',[.5 .1 .45 .85],...
        'Title','Axis Labels');
    handles.edit_labelY = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.15 .1 .75 .075],...
        'String',settings.labelY);
    uicontrol('Style','text',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.1 .085 .04 .075],...
        'HorizontalAlignment','Left',...
        'FontSize',12,...
        'String','Y');
    handles.edit_labelX = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.15 .2 .75 .075],...
        'String',settings.labelX);
    uicontrol('Style','text',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.1 .185 .04 .075],...
        'HorizontalAlignment','Left',...
        'FontSize',12,...
        'String','X');
    axes('Parent',panel_right,...
        'Units','normalized',...
        'Position',[.1 .3 .8 .6],...
        'NextPlot','add',...
        'XTick',[],'YTick',[],'Box','on');
    plot([-1,1],[0,0],'k');
    plot([0,0],[-1,1],'k');
    handles.edit_label8 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.35 .325 .3 .075],...
        'String',settings.label8);
    handles.edit_label7 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.525 .5 .3 .075],...
        'String',settings.label7);
    handles.edit_label6 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.175 .5 .3 .075],...
        'String',settings.label6);
    handles.edit_label5 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.575 .565 .3 .075],...
        'String',settings.label5);
    handles.edit_label4 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.125 .565 .3 .075],...
        'String',settings.label4);
    handles.edit_label3 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.525 .7 .3 .075],...
        'String',settings.label3);
    handles.edit_label2 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.175 .7 .3 .075],...
        'String',settings.label2);
    handles.edit_label1 = uicontrol('Style','edit',...
        'Parent',panel_right,...
        'Units','normalized',...
        'Position',[.35 .8 .3 .075],...
        'String',settings.label1);
    align([handles.edit_label8,handles.edit_label7,handles.edit_label5],'none','distribute');
    align([handles.edit_label5,handles.edit_label3,handles.edit_label1],'none','distribute');
    align([handles.edit_label8,handles.edit_label6,handles.edit_label4],'none','distribute');
    align([handles.edit_label4,handles.edit_label2,handles.edit_label1],'none','distribute');
    switch settings.sps
        case 0.25
            set(handles.bgroup_sps,'SelectedObject',handles.sample_1per4);
        case 0.50
            set(handles.bgroup_sps,'SelectedObject',handles.sample_1per2);
        case 1.00
            set(handles.bgroup_sps,'SelectedObject',handles.sample_1per1);
        case 2.00
            set(handles.bgroup_sps,'SelectedObject',handles.sample_2per1);
        case 4.00
            set(handles.bgroup_sps,'SelectedObject',handles.sample_4per1);
    end
    switch settings.mag
        case 1
            set(handles.bgroup_mag,'SelectedObject',handles.mag_1);
        case 10
            set(handles.bgroup_mag,'SelectedObject',handles.mag_10);
        case 100
            set(handles.bgroup_mag,'SelectedObject',handles.mag_100);
        case 1000
            set(handles.bgroup_mag,'SelectedObject',handles.mag_1000);
    end
    set(handles.figure_configure,'Visible','on');
    guidata(handles.figure_configure,handles);
end

function push_submit_Callback(hObject,~)
    handles = guidata(hObject);
    global settings;
    settings.mag = str2double(get(get(handles.bgroup_mag,'SelectedObject'),'string'));
    settings.sps = str2double(get(get(handles.bgroup_sps,'SelectedObject'),'string'));
    settings.labelX = get(handles.edit_labelX,'string');
    settings.labelY = get(handles.edit_labelY,'string');
    settings.label1 = get(handles.edit_label1,'string');
    settings.label2 = get(handles.edit_label2,'string');
    settings.label3 = get(handles.edit_label3,'string');
    settings.label4 = get(handles.edit_label4,'string');
    settings.label5 = get(handles.edit_label5,'string');
    settings.label6 = get(handles.edit_label6,'string');
    settings.label7 = get(handles.edit_label7,'string');
    settings.label8 = get(handles.edit_label8,'string');
    delete(gcf);
    return;
end