function fig_launcher
%LAUNCHER Code for the DARMA launcher window and functions
% License: https://darma.codeplex.com/license

    % Create and center main window
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    handles.figure_launcher = figure( ...
        'Units','normalized', ...
        'Position',[0.30 0.30 0.40 0.40], ...
        'Name','DARMA: Dual Axis Rating and Media Annotation', ...
        'MenuBar','none', ...
        'ToolBar','none', ...
        'NumberTitle','off', ...
        'Visible','on', ...
        'Color',defaultBackground);
    % Create UI elements
    handles.axis_title = axes(...
        'Parent',handles.figure_launcher,...
        'Units','normalized', ...
        'Position',[0.05 0.60 0.90 0.30], ...
        'Color',[0.2 0.2 0.2],...
        'Box','on','XTick',[],'YTick',[],...
        'ButtonDownFcn',@website);
    xlim([-1 1]); ylim([-1 1]);
    text(0,0,'DARMA v3.00','Color',[1 1 1],'FontSize',50,...
        'FontName','cambria','HorizontalAlignment','center',...
        'ButtonDownFcn',@website);
    %TODO: Set 'cdata' to a resized image for each button
    handles.push_collect = uicontrol('Style','pushbutton', ...
        'Parent',handles.figure_launcher, ...
        'Units','Normalized', ...
        'Position',[0.05 0.10 0.25 0.40], ...
        'String','Collect', ...
        'FontSize',18, ...
        'Callback',@push_collect_Callback);
    handles.push_review = uicontrol('Style','pushbutton', ...
        'Parent',handles.figure_launcher, ...
        'Units','Normalized', ...
        'Position',[0.05 0.10 0.25 0.40], ...
        'String','Review', ...
        'FontSize',18, ...
        'Callback',@push_review_Callback);
    handles.push_configure = uicontrol('Style','pushbutton', ...
        'Parent',handles.figure_launcher, ...
        'Units','Normalized', ...
        'Position',[0.70 0.10 0.25 0.40], ...
        'String','Configure', ...
        'FontSize',18, ...
        'Callback',@push_configure_Callback);
    align([handles.push_collect,handles.push_review,handles.push_configure],'distribute','bottom');
    % Configure default settings
    handles.settings.mag = 1000;
    handles.settings.sps = 2;
    handles.settings.labelX = 'Communion';
    handles.settings.labelY = 'Agency';
    handles.settings.label0 = 'Friendly';
    handles.settings.label1 = 'Extraverted';
    handles.settings.label2 = 'Dominant';
    handles.settings.label3 = 'Disagreeable';
    handles.settings.label4 = 'Separate';
    handles.settings.label5 = 'Introverted';
    handles.settings.label6 = 'Submissive';
    handles.settings.label7 = 'Agreeable';
    guidata(handles.figure_launcher,handles);
end

function push_collect_Callback(hObject,~)
    handles = guidata(hObject);
    fig_collect(handles.settings);
end

function push_review_Callback(hObject,~)
    handles = guidata(hObject);
    fig_review(handles.settings);
end

function push_configure_Callback(hObject,~)
    handles = guidata(hObject);
    handles.settings = fig_configure(handles.settings);
    guidata(handles.figure_launcher,handles);
end

function website(~,~)
    choice = questdlg('Open DARMA website in browser?','DARMA','Yes','No','Yes');
    switch choice
        case 'Yes'
            web('http://darma.codeplex.com/','-browser');
        otherwise
            return;
    end
end